import pandas as pd
import numpy as np
import os

def test_model_accuracy():
    risk_file = "data/processed/final_risk_scores.csv"
    
    if not os.path.exists(risk_file):
        print("❌ Error: Final risk scores not found. Please run the training pipeline first.")
        return

    # Load the results generated by the model
    df = pd.read_csv(risk_file)
    
    print("\n" + "="*50)
    print("      MODEL PREDICTION VS GROUND TRUTH TEST")
    print("="*50)
    
    # Pick a few sample cases
    # FLAG 1 = Actual Theft, FLAG 0 = Actual Normal
    samples = []
    
    # Grab a high-confidence theft prediction that is actually theft
    theft_cases = df[(df['FLAG'] == 1) & (df['Risk_Tier'] == 'Theft')].head(2)
    samples.append(theft_cases)
    
    # Grab a high-confidence normal prediction that is actually normal
    normal_cases = df[(df['FLAG'] == 0) & (df['Risk_Tier'] == 'Normal')].head(2)
    samples.append(normal_cases)
    
    # Grab a potential error (False Negative)
    missed_cases = df[(df['FLAG'] == 1) & (df['Risk_Tier'] == 'Normal')].head(1)
    samples.append(missed_cases)

    test_df = pd.concat(samples).reset_index(drop=True)

    for i, row in test_df.iterrows():
        actual = "🔴 THEFT" if row['FLAG'] == 1 else "🟢 NORMAL"
        pred_tier = row['Risk_Tier']
        score = row['Final_Risk_Score']
        
        status = "✅ CORRECT" if (row['FLAG'] == 1 and score > 60) or (row['FLAG'] == 0 and score <= 30) else "❌ WRONG/UNSURE"
        
        print(f"\n[Test #{i+1}] Consumer ID: {row['CONS_NO']}")
        print(f"   - Actual Ground Truth : {actual}")
        print(f"   - Model Prediction    : {pred_tier} (Score: {score:.2f}/100)")
        print(f"   - Result              : {status}")
        if row['Top_Flagged_Rule'] != "None":
            print(f"   - Primary Reason      : {row['Top_Flagged_Rule']}")

    print("\n" + "="*50)
    print("Test complete. Use the dashboard to inspect these consumers visually.")

if __name__ == "__main__":
    test_model_accuracy()
